/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_henjiandan_MainActivity */

#ifndef _Included_com_example_henjiandan_MainActivity
#define _Included_com_example_henjiandan_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_henjiandan_MainActivity
 * Method:    check
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL jNI_OnLoad(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
